name: Test Workflow

on:
  push:
    branches:
      - master  # or main, depending on your default branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo email 22f3000710@ds.study.iitm.ac.in
        run: echo "Hello from GitHub Actions!"
